# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discount-function-app"
client_id = "629ef6d7e9e8fc3e41b98081db03cd53"
application_url = "https://36a7-2409-40c2-112-6c14-307a-60f-a36f-83ea.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [
  "https://36a7-2409-40c2-112-6c14-307a-60f-a36f-83ea.ngrok-free.app/auth/callback",
  "https://36a7-2409-40c2-112-6c14-307a-60f-a36f-83ea.ngrok-free.app/auth/shopify/callback",
  "https://36a7-2409-40c2-112-6c14-307a-60f-a36f-83ea.ngrok-free.app/api/auth/callback",
  "https://36a7-2409-40c2-112-6c14-307a-60f-a36f-83ea.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "testorderdemo.myshopify.com"
